### ISSUE TITLE
website_event_contact_person

### ISSUE THREAD

**Issue by andhit-r** [open-synergy/event#2]
Dependensi:
- website_event
- event_contact_person

Acceptance Criteria:
- [ ] Ditampilkan hanya jika field **contact_person_ids** diisi
- [ ] Format tampilan sama seperti organizer
- [ ] Diloop sebanyak data contact person
- [ ]  Diletakan di bawah organizer

Posisi pada website:

![posisi_cp_pada_website](https://cloud.githubusercontent.com/assets/1947376/13184283/779ecc00-d76d-11e5-9425-0cd4a42d72e1.png)

Mockup:

![mockup_contact_person](https://cloud.githubusercontent.com/assets/1947376/13184288/825726ec-d76d-11e5-91d4-7f0077e6b5da.png)

**Comment by andhit-r** [comment]
cc @azmimr67 @mikevhe18

**Comment by mikevhe18** [comment]
PR TO OCA [#43](https://github.com/OCA/event/pull/43)
